In [14]:
import sys

print(sys.executable)
print(sys.version)

c:\Users\lahan\Documents\E-Commerce-Sales-Customer-Analytics\.venv\Scripts\python.exe
3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]

# E-Commerce Sales & Customer Analytics

## 01 — Data Quality Inspection

This notebook performs the initial inspection of the Online Retail II dataset.

### Objectives
- Load the raw transaction data
- Understand the dataset structure
- Inspect data types
- Identify missing values
- Identify duplicates
- Investigate cancellations and returns
- Check invalid quantities and prices
- Establish the date range
- Prepare the dataset for cleaning

In [15]:
import pandas as pd
import numpy as np

print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

Pandas version: 3.0.5
NumPy version: 2.4.6

In [16]:
file_path = "../data/online_retail_II.xlsx"

print("Dataset path:", file_path)

Dataset path: ../data/online_retail_II.xlsx

In [17]:
df_2009 = pd.read_excel(
    file_path,
    sheet_name="Year 2009-2010"
)

print("Rows:", f"{len(df_2009):,}")
print("Columns:", df_2009.shape[1])

Rows: 525,461
Columns: 8

In [18]:
df_2009.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [19]:
df_2009.info()

<class 'pandas.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      525461 non-null  object
 1   StockCode    525461 non-null  object
 2   Description  522533 non-null  object
 3   Quantity     525461 non-null  int64
 4   InvoiceDate  525461 non-null  datetime64[us]
 5   Price        525461 non-null  float64
 6   Customer ID  417534 non-null  float64
 7   Country      525461 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 32.1+ MB

In [20]:
missing = pd.DataFrame({
    "Missing Values": df_2009.isnull().sum(),
    "Missing %": (df_2009.isnull().mean() * 100).round(2)
})

missing

             Missing Values  Missing %
Invoice                   0       0.00
StockCode                 0       0.00
Description            2928       0.56
Quantity                  0       0.00
InvoiceDate               0       0.00
Price                     0       0.00
Customer ID          107927      20.54
Country                   0       0.00

In [21]:
duplicate_count = df_2009.duplicated().sum()

print("Duplicate rows:", f"{duplicate_count:,}")

Duplicate rows: 6,865

In [22]:
cancelled = df_2009["Invoice"].astype(str).str.startswith("C")

print("Cancelled transactions:", f"{cancelled.sum():,}")
print("Cancelled %:", f"{cancelled.mean() * 100:.2f}%")

Cancelled transactions: 10,206
Cancelled %: 1.94%

In [23]:
print("Negative quantities:", (df_2009["Quantity"] < 0).sum())
print("Zero quantities:", (df_2009["Quantity"] == 0).sum())
print("Positive quantities:", (df_2009["Quantity"] > 0).sum())

Negative quantities: 12326
Zero quantities: 0
Positive quantities: 513135

In [24]:
print("Negative prices:", (df_2009["Price"] < 0).sum())
print("Zero prices:", (df_2009["Price"] == 0).sum())
print("Positive prices:", (df_2009["Price"] > 0).sum())

Negative prices: 3
Zero prices: 3687
Positive prices: 521771

In [25]:
print("First transaction:", df_2009["InvoiceDate"].min())
print("Last transaction:", df_2009["InvoiceDate"].max())

First transaction: 2009-12-01 07:45:00
Last transaction: 2010-12-09 20:01:00

In [26]:
df_2009["Revenue"] = df_2009["Quantity"] * df_2009["Price"]

print("Total transaction value:", f"£{df_2009['Revenue'].sum():,.2f}")

Total transaction value: £9,539,484.63

In [27]:
df_2009["Revenue"].describe()

count    525461.000000
mean         18.154506
std         160.333083
min      -53594.360000
25%           3.750000
50%           9.950000
75%          17.700000
max       25111.090000
Name: Revenue, dtype: float64

In [28]:
df_2010 = pd.read_excel(
    file_path,
    sheet_name="Year 2010-2011"
)

print("Rows:", f"{len(df_2010):,}")
print("Columns:", df_2010.shape[1])

Rows: 541,910
Columns: 8

In [29]:
df_2010.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [30]:
df_2010.info()

<class 'pandas.DataFrame'>
RangeIndex: 541910 entries, 0 to 541909
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      541910 non-null  object
 1   StockCode    541910 non-null  object
 2   Description  540456 non-null  object
 3   Quantity     541910 non-null  int64
 4   InvoiceDate  541910 non-null  datetime64[us]
 5   Price        541910 non-null  float64
 6   Customer ID  406830 non-null  float64
 7   Country      541910 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 33.1+ MB

In [31]:
missing_2010 = pd.DataFrame({
    "Missing Values": df_2010.isnull().sum(),
    "Missing %": (df_2010.isnull().mean() * 100).round(2)
})

missing_2010

             Missing Values  Missing %
Invoice                   0       0.00
StockCode                 0       0.00
Description            1454       0.27
Quantity                  0       0.00
InvoiceDate               0       0.00
Price                     0       0.00
Customer ID          135080      24.93
Country                   0       0.00

In [32]:
duplicate_count_2010 = df_2010.duplicated().sum()

cancelled_2010 = (
    df_2010["Invoice"]
    .astype(str)
    .str.startswith("C")
)

print("Duplicate rows:", f"{duplicate_count_2010:,}")
print("Cancelled transactions:", f"{cancelled_2010.sum():,}")
print("Cancelled %:", f"{cancelled_2010.mean() * 100:.2f}%")

Duplicate rows: 5,268
Cancelled transactions: 9,288
Cancelled %: 1.71%

In [33]:
print("Negative quantities:", (df_2010["Quantity"] < 0).sum())
print("Zero quantities:", (df_2010["Quantity"] == 0).sum())
print("Positive quantities:", (df_2010["Quantity"] > 0).sum())

print()

print("Negative prices:", (df_2010["Price"] < 0).sum())
print("Zero prices:", (df_2010["Price"] == 0).sum())
print("Positive prices:", (df_2010["Price"] > 0).sum())

Negative quantities: 10624
Zero quantities: 0
Positive quantities: 531286

Negative prices: 2
Zero prices: 2515
Positive prices: 539393

In [34]:
print("First transaction:", df_2010["InvoiceDate"].min())
print("Last transaction:", df_2010["InvoiceDate"].max())

First transaction: 2010-12-01 08:26:00
Last transaction: 2011-12-09 12:50:00

In [35]:
df_2010["Revenue"] = df_2010["Quantity"] * df_2010["Price"]

print(
    "Total transaction value:",
    f"£{df_2010['Revenue'].sum():,.2f}"
)

Total transaction value: £9,747,765.93

In [36]:
df_2010["Revenue"].describe()

count    541910.000000
mean         17.987795
std         378.810474
min     -168469.600000
25%           3.400000
50%           9.750000
75%          17.400000
max      168469.600000
Name: Revenue, dtype: float64